In [1]:
# ===머신러닝====
import pickle
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

In [11]:
import pandas as pd

# def load_dataset():

#    # 현재 파일(child.py)의 경로를 기준으로 데이터셋 경로를 생성
#     current_path = os.path.dirname(__file__)  # utils 폴더 경로
#     dataset_path = os.path.join(current_path, '../datasets/child_abuse_dataset_0_7.csv')  # datasets 폴더 내 파일
#     try:
#         df = pd.read_csv(dataset_path)  # 데이터 로드


# 데이터 로드
df = pd.read_csv("../datasets/child_abuse_dataset_0_7.csv")

# gender 컬럼 타입 변환 (object > int)
df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})

# x,y 설정
X = df.iloc[:, :-1]
y = df['child_abuse_detected']

#데이터 분리(Dataset Partitioning)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# 모델 만들기
model = DecisionTreeClassifier(max_depth=5, random_state=42)  # 과적합 방지 위해 max_depth 설정)

#훈련
model.fit(X_train,y_train)

# 예측
preds = model.predict(X_test)

#평가
accuracy = accuracy_score(y_test, preds)
print(f"Accuracy: {accuracy}")

# 모델 저장
with open('ml_model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("모델이 성공적으로 저장되었습니다.")

Accuracy: 0.95
모델이 성공적으로 저장되었습니다.

In [10]:
df

,age,gender,bruises,fractures,malnutrition,poor_hygiene,head_injuries,self_harm_marks,domestic_violence,previous_reports,child_abuse_detected
0,0,1,3,0,1,1,0,0,0,0,1
1,5,1,5,0,0,0,0,0,0,1,0
2,6,0,0,0,0,0,0,0,0,0,0
3,4,1,4,0,1,1,0,0,0,1,1
4,7,1,6,0,0,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
9995,4,0,5,0,0,0,0,0,0,0,0
9996,1,0,3,0,0,0,0,0,1,0,1
9997,5,0,1,0,0,0,0,0,0,0,0
9998,1,1,2,0,0,0,0,0,0,0,0
9999,4,0,4,0,0,0,0,0,0,0,0